### Configuração para integração com banco em memória h2
spring:
  datasource:
    url: jdbc:h2:file:~/dio
    driverClassName: org.h2.Driver
    username: sa
    password:

  ## H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  ## JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

## Configuração para integração com banco PostgreSQL no HEROKU
#server:
#  port: 8080
#  servlet:
#    context-path: /personapi
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url:
#    username:
#    password:
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
